import{initialize,isConfigured,onUser,signIn,logOut,createRecord,listRecords,updateRecord,deleteRecord,createCalendarEvent,listCalendarEvents,calendarConnected,user}from'./store.js?v=1.6';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={page:'inicio',patients:[],services:[],psychometrics:[],loading:false};
let calendarSyncTimer=null;
const titles={inicio:'Resumen general',agenda:'Agenda',servicios:'Registrar servicio',pacientes:'Pacientes',psicometria:'Psicometría',historial:'Historial de servicios',estadisticas:'Estadísticas',configuracion:'Configuración'};
const THEME_KEY='clinica_theme_v1';
function selectedTheme(){return localStorage.getItem(THEME_KEY)||'system'}
function applyTheme(theme=selectedTheme()){const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light'}
applyTheme();matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(selectedTheme()==='system')applyTheme()});
const serviceLabels={session:'Sesión psicológica',workshop:'Taller o capacitación',crisis:'Intervención en crisis',activity:'Actividad institucional',followup:'Seguimiento telefónico'};
const statusClass=s=>s==='Realizado'||s==='Realizada'||s==='Entregado'?'done':s==='Cancelado'||s==='Cancelada'||s==='Ausencia'?'cancel':s==='Emergencia'?'warn':'';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>{if(!d)return'—';const x=new Date(`${d}T12:00:00`);return new Intl.DateTimeFormat('es-GT',{day:'numeric',month:'short',year:'numeric'}).format(x)};
const initials=n=>(n||'PS').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open')}
document.addEventListener('click',e=>{if(e.target.matches('[data-close]')||e.target===$('#modal'))closeModal()});

async function boot(){
  $('#dateLabel').textContent=new Intl.DateTimeFormat('es-GT',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
  if(!isConfigured()){showGate('La conexión segura no está disponible. Contacta al administrador.');return}
  try{await initialize();onUser(async u=>{if(!u){showGate('Inicia sesión con una cuenta autorizada para continuar.');return}showApp(u);await loadAll()})}catch(error){console.error(error);showGate('No fue posible conectar con el sistema. Intenta de nuevo más tarde.')}
}
function showGate(text,setup=false){$('#gate').classList.remove('hidden');$('#app').classList.add('hidden');$('#gateText').textContent=text;$('#signInBtn').classList.toggle('hidden',setup)}
function showApp(u){$('#gate').classList.add('hidden');$('#app').classList.remove('hidden');$('#userName').textContent=u.displayName||'Profesional';$('#userEmail').textContent=u.email||'';$('#avatar').textContent=initials(u.displayName);render()}
$('#signInBtn').onclick=async()=>{const button=$('#signInBtn'),original=button.innerHTML;button.disabled=true;button.textContent='Abriendo acceso de Google…';try{await signIn(false)}catch(e){console.error(e);const messages={'auth/popup-closed-by-user':'Se cerró la ventana de Google antes de terminar.','auth/unauthorized-domain':'Este sitio todavía no está autorizado en Firebase.','auth/network-request-failed':'No se pudo conectar con Google. Revisa tu conexión.'};toast(messages[e?.code]||`No se pudo iniciar sesión${e?.code?` (${e.code})`:''}`)}finally{button.disabled=false;button.innerHTML=original}};
$('#signInPopupBtn').onclick=async()=>{const button=$('#signInPopupBtn'),original=button.textContent;button.disabled=true;button.textContent='Abriendo ventana…';try{await signIn(false,'popup')}catch(e){console.error(e);const messages={'auth/popup-closed-by-user':'Se cerró la ventana antes de terminar.','auth/popup-blocked':'El navegador bloqueó la ventana emergente.','auth/network-request-failed':'No se pudo conectar con Google.'};toast(messages[e?.code]||`No se pudo iniciar sesión${e?.code?` (${e.code})`:''}`)}finally{button.disabled=false;button.textContent=original}};
$('#signOutBtn').onclick=()=>logOut();

async function loadAll(){state.loading=true;render();try{[state.services,state.patients,state.psychometrics]=await Promise.all([listRecords('services'),listRecords('patients'),listRecords('psychometrics')]);$('#syncState').textContent='● Sincronizado'}catch(e){console.error(e);if(e?.code==='permission-denied'){await logOut();showGate('Esta cuenta no está autorizada. Utiliza el correo asignado a la clínica.');return}$('#syncState').textContent='● Error de conexión';toast('No se pudieron cargar los datos')}finally{state.loading=false;render()}}
function navigate(page){state.page=page;$('#pageTitle').textContent=titles[page];$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));render();scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)navigate(b.dataset.page)});
function render(){if($('#app').classList.contains('hidden'))return;const el=$('#content');if(state.loading){el.innerHTML='<div class="card empty">Cargando información…</div>';return}el.innerHTML=({inicio:renderHome,agenda:renderAgenda,servicios:renderServices,pacientes:renderPatients,psicometria:renderPsychometrics,historial:renderHistory,estadisticas:renderStats,configuracion:renderSettings}[state.page])();bindPage()}

function monthItems(items,dateKey='date'){const now=new Date(),m=now.getMonth(),y=now.getFullYear();return items.filter(x=>{const d=new Date(`${x[dateKey]}T12:00:00`);return d.getMonth()===m&&d.getFullYear()===y})}
function counts(){const all=monthItems(state.services),by=t=>all.filter(x=>x.type===t);return{all:all.length,sessions:by('session').length,patients:new Set(by('session').map(x=>x.patientId).filter(Boolean)).size,followups:by('followup').length,workshops:by('workshop').length,crises:by('crisis').length,activities:by('activity').length,psych:monthItems(state.psychometrics,'evaluationDate').length}}
function calendarType(title=''){const t=title.toLowerCase();return t.includes('taller')||t.includes('capacitación')?'workshop':t.includes('crisis')||t.includes('emergencia')?'crisis':t.includes('actividad')||t.includes('reunión')||t.includes('simposio')?'activity':'session'}
function calendarRecord(event){const start=event.start?.dateTime?new Date(event.start.dateTime):new Date(`${event.start?.date}T09:00:00`),end=event.end?.dateTime?new Date(event.end.dateTime):new Date(start.getTime()+50*60000),title=event.summary||'Cita de Google Calendar',type=calendarType(title),patientName=title.includes(':')?title.split(':').slice(1).join(':').trim():title;return{type,title,patientName,date:start.toLocaleDateString('en-CA',{timeZone:'America/Guatemala'}),time:event.start?.dateTime?start.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Guatemala'}):'',durationMinutes:Math.max(1,Math.round((end-start)/60000)),modality:event.hangoutLink||event.conferenceData?'Virtual':'Presencial',status:end<new Date()?'Realizado':'Programado',notes:event.description||'',location:event.location||'',calendarEventId:event.id,calendarSource:'Google Calendar'}}
async function syncCalendar({silent=false}={}){try{const events=await listCalendarEvents(),known=new Set(state.services.map(x=>x.calendarEventId).filter(Boolean));let added=0;for(const event of events){if(known.has(event.id))continue;await createRecord('services',calendarRecord(event));known.add(event.id);added++}if(added)await loadAll();if(!silent)toast(added?`${added} eventos importados`:'Calendar ya está sincronizado');return added}catch(e){console.error(e);if(!silent)toast(e.message?.startsWith('CALENDAR_403')?'Activa la API de Google Calendar':'No se pudo sincronizar Calendar');throw e}}
function startCalendarSync(){clearInterval(calendarSyncTimer);calendarSyncTimer=setInterval(()=>{if(calendarConnected())syncCalendar({silent:true}).catch(()=>{})},5*60*1000)}
function renderHome(){const c=counts(),today=new Date().toISOString().slice(0,10),upcoming=state.services.filter(x=>x.date===today).sort((a,b)=>(a.time||'').localeCompare(b.time||''));const max=Math.max(c.sessions,c.followups,c.workshops,c.crises,c.activities,c.psych,1);return`<div class="grid two"><section class="card"><div class="section-head"><div><p class="kicker">Servicios prestados</p><h2>Resumen del mes</h2></div><button class="btn soft" data-page="estadisticas">Ver estadísticas</button></div><div class="metrics"><div class="metric primary"><small>Total de servicios</small><strong>${c.all+c.psych}</strong></div><div class="metric"><small>Sesiones</small><strong>${c.sessions}</strong></div><div class="metric"><small>Pacientes atendidos</small><strong>${c.patients}</strong></div><div class="metric"><small>Seguimientos</small><strong>${c.followups}</strong></div></div><div class="service-bars">${[['Sesiones',c.sessions],['Seguimientos',c.followups],['Talleres',c.workshops],['Intervenciones',c.crises],['Actividades',c.activities],['Psicometría',c.psych]].map(([n,v])=>`<div class="bar-row"><span>${n}</span><b>${v}</b><div class="track"><i style="--value:${v/max*100}%"></i></div></div>`).join('')}</div></section><section class="card today-card"><p class="kicker">Agenda de hoy</p><div class="big">${upcoming.length} actividades</div><p>${upcoming.length?'Consulta los servicios programados y pendientes.':'No hay servicios registrados para hoy.'}</p><button class="btn wide" data-page="agenda">Abrir agenda</button><button class="btn wide" id="calendarAuth" style="margin-top:9px">${calendarConnected()?'Sincronizar Google Calendar':'Conectar Google Calendar'}</button></section></div><section class="card" style="margin-top:18px"><div class="section-head"><div><p class="kicker">Hoy</p><h2>Servicios programados</h2></div><button class="btn primary" data-page="servicios">＋ Registrar</button></div>${upcoming.length?upcoming.map(agendaRow).join(''):'<div class="empty">No hay actividades para hoy.</div>'}</section>`}
function agendaRow(x){return`<div class="agenda-item"><b>${esc(x.time||'—')}</b><div><strong>${esc(serviceLabels[x.type]||x.type)}${x.patientName?' · '+esc(x.patientName):''}</strong><small>${esc(x.modality||'Sin modalidad')}${x.durationMinutes?' · '+esc(x.durationMinutes)+' min':''}</small></div><span class="badge ${statusClass(x.status)}">${esc(x.status||'Registrado')}</span></div>`}

function renderAgenda(){const rows=[...state.services].sort((a,b)=>`${a.date||''}${a.time||''}`.localeCompare(`${b.date||''}${b.time||''}`));return`<section class="card"><div class="section-head"><div><p class="kicker">Agenda</p><h2>Servicios por fecha</h2></div><button class="btn primary" data-page="servicios">＋ Nuevo servicio</button></div><div class="filters"><input id="agendaSearch" placeholder="Buscar persona o actividad"><input id="agendaDate" type="date"><select id="agendaType"><option value="">Todos los servicios</option>${Object.entries(serviceLabels).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><select id="agendaStatus"><option value="">Todos los estados</option><option>Programado</option><option>Realizado</option><option>Cancelado</option></select><button class="btn" id="agendaFilter">Filtrar</button></div><div id="agendaRows">${agendaTable(rows)}</div></section>`}
function agendaTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Fecha y hora</th><th>Servicio</th><th>Persona o grupo</th><th>Modalidad</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${fmt(x.date)} · ${esc(x.time||'—')}</td><td>${esc(serviceLabels[x.type])}</td><td>${esc(x.patientName||x.audience||x.title||'—')}</td><td>${esc(x.modality||'—')}</td><td><span class="badge ${statusClass(x.status)}">${esc(x.status||'Registrado')}</span></td><td>${rowActions('services',x.id)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No se encontraron servicios.</div>'}

function renderServices(){return`<section class="card"><p class="kicker">Nuevo registro</p><h2>Registrar servicio prestado</h2><div class="type-grid">${Object.entries({session:['◉','Sesión'],workshop:['▣','Taller'],crisis:['!','Intervención'],activity:['▤','Actividad'],followup:['☎','Seguimiento']}).map(([k,[i,n]],idx)=>`<button class="type-btn ${idx===0?'active':''}" data-type="${k}"><strong>${i}</strong>${n}</button>`).join('')}</div><div id="serviceFormWrap">${serviceForm('session')}</div></section>`}
function patientOptions(selected=''){return`<option value="">Seleccionar paciente</option>${state.patients.map(p=>`<option value="${p.id}" ${selected===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}`}
const input=(label,name,type='text',value='',full='')=>`<div class="field ${full}"><label>${label}</label><input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0"':''}></div>`;
const select=(label,name,options,value='',full='')=>`<div class="field ${full}"><label>${label}</label><select name="${name}">${options.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`;
const textarea=(label,name,value='',full='full')=>`<div class="field ${full}"><label>${label}</label><textarea name="${name}">${esc(value)}</textarea></div>`;
function serviceForm(type,data={}){let body='';if(type==='session')body=`<div class="field full"><label>Paciente</label><select name="patientId" required>${patientOptions(data.patientId)}</select></div>${input('Fecha','date','date',data.date)}${input('Hora','time','time',data.time)}${input('Duración en minutos','durationMinutes','number',data.durationMinutes||50)}${select('Modalidad','modality',['Presencial','Virtual'],data.modality)}${select('Estado','status',['Programado','Realizado','Cancelado','Ausencia'],data.status)}${select('Pago','payment',['No aplica','Pagado','Pendiente'],data.payment||'No aplica')}${textarea('Observaciones','notes',data.notes)}`;
if(type==='workshop')body=`${input('Tema','title','text',data.title,'full')}${input('Fecha','date','date',data.date)}${input('Hora','time','time',data.time)}${input('Duración en minutos','durationMinutes','number',data.durationMinutes)}${input('Número de asistentes','attendees','number',data.attendees)}${select('Modalidad','modality',['Presencial','Virtual','Híbrida'],data.modality)}${input('Dirigido a','audience','text',data.audience,'full')}${select('Estado','status',['Programado','Realizado','Cancelado'],data.status)}`;
if(type==='crisis')body=`${textarea('Motivo del incidente','reason',data.reason)}${input('Fecha','date','date',data.date)}${input('Número de personas atendidas','peopleCount','number',data.peopleCount)}${input('Hora del aviso','noticeTime','time',data.noticeTime)}${input('Hora efectiva','time','time',data.time)}${input('Hora de retiro','endTime','time',data.endTime)}${textarea('Nombres y observaciones individuales','individualNotes',data.individualNotes)}<input type="hidden" name="status" value="Realizado"><input type="hidden" name="modality" value="Presencial">`;
if(type==='activity')body=`${select('Tipo de actividad','activityType',['Académica','Comisión OBA','Comisión CCBICA','Coordinación internacional','Designación','Otra'],data.activityType,'full')}${input('Número de oficio','officeNumber','text',data.officeNumber)}${input('Fecha','date','date',data.date)}${input('Hora','time','time',data.time)}${select('Modalidad','modality',['Presencial','Virtual','Híbrida'],data.modality)}${textarea('Motivo','reason',data.reason)}${input('Solicitante','requester','text',data.requester)}${input('Contacto del solicitante','requesterContact','text',data.requesterContact)}${textarea('Observaciones','notes',data.notes)}${select('Estado','status',['Programado','Realizado','Cancelado'],data.status)}`;
if(type==='followup')body=`<div class="field full"><label>Paciente</label><select name="patientId" required>${patientOptions(data.patientId)}</select></div>${input('Fecha','date','date',data.date)}${input('Hora','time','time',data.time)}${select('Resultado','status',['Contacto realizado','Sin respuesta','Reprogramar'],data.status)}${textarea('Observaciones','notes',data.notes)}`;
return`<form id="serviceForm" data-kind="${type}" data-id="${data.id||''}"><div class="form-grid">${body}<label class="field full" style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input style="width:auto" type="checkbox" name="calendar" ${data.calendarEventId?'checked disabled':''}> Crear también en Google Calendar</label></div><div class="form-actions"><button type="reset" class="btn">Limpiar</button><button class="btn primary">${data.id?'Guardar cambios':'Guardar servicio'}</button></div></form>`}

function renderPatients(){return`<section class="card"><div class="section-head"><div><p class="kicker">Directorio</p><h2>Pacientes</h2></div><button class="btn primary" id="addPatient">＋ Nuevo paciente</button></div><div class="filters"><input id="patientSearch" placeholder="Buscar por nombre, categoría o estación"><span></span><span></span><span></span><button class="btn" id="patientFilter">Buscar</button></div><div class="patients" id="patientCards">${patientCards(state.patients)}</div></section>`}
function patientCards(rows){return rows.length?rows.map(p=>`<article class="patient-card"><div class="avatar">${initials(p.name)}</div><h3>${esc(p.name)}</h3><p>${esc(p.workStatus||'Sin categoría')}${p.station?' · '+esc(p.station):''}</p><p>${esc(p.phone||'Sin teléfono')}</p><footer><span class="badge ${p.status==='Activo'?'done':''}">${esc(p.status||'Activo')}</span><span class="actions"><button class="icon-btn" data-edit="patients" data-id="${p.id}">Editar</button><button class="icon-btn delete" data-delete="patients" data-id="${p.id}">Eliminar</button></span></footer></article>`).join(''):'<div class="empty">Aún no hay pacientes registrados.</div>'}
function patientForm(p={}){return`<p class="kicker">Ficha de paciente</p><h2>${p.id?'Editar paciente':'Nuevo paciente'}</h2><form id="patientForm" data-id="${p.id||''}"><div class="form-grid">${input('Nombre completo','name','text',p.name,'full')}${input('Teléfono','phone','tel',p.phone)}${select('Estado del proceso','status',['Activo','Inactivo','Alta'],p.status||'Activo')}${select('Situación laboral','workStatus',['Permanente','Ad honorem','Administrativo','Familiar','Otro'],p.workStatus)}${input('Estación, turno o área','station','text',p.station)}${textarea('Motivo de consulta','consultationReason',p.consultationReason)}${input('Contacto de emergencia','emergencyName','text',p.emergencyName)}${input('Número de emergencia','emergencyPhone','tel',p.emergencyPhone)}</div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar paciente</button></div></form>`}

function renderPsychometrics(){return`<section class="card"><div class="section-head"><div><p class="kicker">Evaluaciones</p><h2>Psicometría</h2></div><button class="btn primary" id="addPsych">＋ Nueva evaluación</button></div><div class="filters"><input id="psychSearch" placeholder="Buscar paciente"><input id="psychDate" type="date"><select id="psychStatus"><option value="">Todos los estados</option><option>Programada</option><option>Evaluada</option><option>No evaluada</option></select><select id="reportStatus"><option value="">Todos los informes</option><option>Pendiente</option><option>Entregado</option></select><button class="btn" id="psychFilter">Filtrar</button></div><div id="psychRows">${psychTable(state.psychometrics)}</div></section>`}
function psychTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Paciente</th><th>Fecha de evaluación</th><th>Evaluación</th><th>Informe</th><th>Fecha de entrega</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.patientName||'—')}</td><td>${fmt(x.evaluationDate)}</td><td><span class="badge ${x.evaluationStatus==='Evaluada'?'done':''}">${esc(x.evaluationStatus)}</span></td><td>${esc(x.reportStatus)}</td><td>${fmt(x.reportDate)}</td><td>${rowActions('psychometrics',x.id)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Aún no hay evaluaciones registradas.</div>'}
function psychForm(x={}){return`<p class="kicker">Evaluación psicométrica</p><h2>${x.id?'Editar evaluación':'Nuevo registro'}</h2><form id="psychForm" data-id="${x.id||''}"><div class="form-grid"><div class="field full"><label>Paciente</label><select name="patientId" required>${patientOptions(x.patientId)}</select></div>${input('Fecha de evaluación','evaluationDate','date',x.evaluationDate)}${select('Estado de evaluación','evaluationStatus',['Programada','Evaluada','No evaluada'],x.evaluationStatus)}${select('Estado del informe','reportStatus',['Pendiente','Entregado'],x.reportStatus)}${input('Fecha de entrega','reportDate','date',x.reportDate)}${textarea('Observaciones','notes',x.notes)}</div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Guardar evaluación</button></div></form>`}

function renderHistory(){return`<section class="card"><div class="section-head"><div><p class="kicker">Registro completo</p><h2>Historial de servicios</h2></div><button class="btn soft" id="exportBtn">⇩ Exportar</button></div><div class="filters"><input id="historySearch" placeholder="Paciente, tema o solicitante"><input id="historyDate" type="date"><select id="historyStatus"><option value="">Todos los estados</option><option>Programado</option><option>Realizado</option><option>Cancelado</option></select><select id="historyModality"><option value="">Todas las modalidades</option><option>Presencial</option><option>Virtual</option><option>Híbrida</option></select><button class="btn" id="historyFilter">Filtrar</button></div><div id="historyRows">${historyTable(state.services)}</div></section>`}
function historyTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Servicio</th><th>Paciente o destinatario</th><th>Modalidad</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${fmt(x.date)}</td><td>${esc(serviceLabels[x.type])}</td><td>${esc(x.patientName||x.audience||x.title||x.requester||'—')}</td><td>${esc(x.modality||'—')}</td><td><span class="badge ${statusClass(x.status)}">${esc(x.status||'Registrado')}</span></td><td>${rowActions('services',x.id)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Aún no hay servicios registrados.</div>'}
function rowActions(kind,id){return`<div class="actions"><button class="icon-btn" data-edit="${kind}" data-id="${id}">Editar</button><button class="icon-btn delete" data-delete="${kind}" data-id="${id}">Eliminar</button></div>`}

function renderStats(){const c=counts(),items=[['Sesiones',c.sessions,'session'],['Seguimientos',c.followups,'followup'],['Talleres',c.workshops,'workshop'],['Intervenciones en crisis',c.crises,'crisis'],['Actividades',c.activities,'activity'],['Psicometría',c.psych,'psych'],['Pacientes activos',state.patients.filter(x=>x.status!=='Inactivo').length,'patients']];return`<section class="card"><div class="section-head"><div><p class="kicker">Análisis del mes</p><h2>Estadísticas</h2></div><button class="btn soft" id="exportBtn">⇩ Exportar</button></div><div class="stats">${items.map(([n,v,k])=>`<article class="stat"><small>${n}</small><strong>${v}</strong><button data-stat="${k}">Ver detalle</button></article>`).join('')}</div></section>`}

function renderSettings(){const theme=selectedTheme();return`<section class="card"><p class="kicker">Preferencias personales</p><h2>Apariencia</h2><p style="color:var(--muted)">Elige cómo quieres ver el sistema en este dispositivo.</p><div class="settings-grid">${[['light','Claro'],['dark','Oscuro'],['system','Usar el sistema']].map(([value,label])=>`<button class="theme-option ${theme===value?'active':''}" data-theme-option="${value}"><div class="theme-preview ${value}"></div><strong>${label}</strong></button>`).join('')}</div></section><section class="card" style="margin-top:18px"><p class="kicker">Cuenta</p><h2>Acceso y seguridad</h2><div class="setting-row"><div><strong>Cuenta activa</strong><p>${esc(user()?.email||'')}</p></div><span class="badge done">Autorizada</span></div><div class="setting-row"><div><strong>Sesión de Google</strong><p>Tu identidad protege el acceso a la información clínica.</p></div><button class="btn" id="settingsSignOut">Cerrar sesión</button></div></section>`}

function bindPage(){
  $$('[data-theme-option]').forEach(b=>b.onclick=()=>{localStorage.setItem(THEME_KEY,b.dataset.themeOption);applyTheme();render();toast('Apariencia actualizada')});
  $('#settingsSignOut')?.addEventListener('click',()=>logOut());
  $$('[data-type]').forEach(b=>b.onclick=()=>{$$('[data-type]').forEach(x=>x.classList.toggle('active',x===b));$('#serviceFormWrap').innerHTML=serviceForm(b.dataset.type);bindServiceForm()});bindServiceForm();
  $('#addPatient')?.addEventListener('click',()=>{openModal(patientForm());bindPatientForm()});$('#addPsych')?.addEventListener('click',()=>{openModal(psychForm());bindPsychForm()});
  $('#calendarAuth')?.addEventListener('click',async()=>{try{if(!calendarConnected())await signIn(true);await syncCalendar();startCalendarSync();render()}catch(e){console.error(e)}});
  $('#agendaFilter')?.addEventListener('click',()=>{const q=$('#agendaSearch').value.toLowerCase(),date=$('#agendaDate').value,type=$('#agendaType').value,status=$('#agendaStatus').value;const rows=state.services.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!date||x.date===date)&&(!type||x.type===type)&&(!status||x.status===status));$('#agendaRows').innerHTML=agendaTable(rows);bindActions()});
  $('#patientFilter')?.addEventListener('click',()=>{const q=$('#patientSearch').value.toLowerCase();$('#patientCards').innerHTML=patientCards(state.patients.filter(x=>JSON.stringify(x).toLowerCase().includes(q)));bindActions()});
  $('#psychFilter')?.addEventListener('click',()=>{const q=$('#psychSearch').value.toLowerCase(),date=$('#psychDate').value,status=$('#psychStatus').value,report=$('#reportStatus').value;$('#psychRows').innerHTML=psychTable(state.psychometrics.filter(x=>(!q||(x.patientName||'').toLowerCase().includes(q))&&(!date||x.evaluationDate===date)&&(!status||x.evaluationStatus===status)&&(!report||x.reportStatus===report)));bindActions()});
  $('#historyFilter')?.addEventListener('click',()=>{const q=$('#historySearch').value.toLowerCase(),date=$('#historyDate').value,status=$('#historyStatus').value,mod=$('#historyModality').value;$('#historyRows').innerHTML=historyTable(state.services.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!date||x.date===date)&&(!status||x.status===status)&&(!mod||x.modality===mod)));bindActions()});
  $('#exportBtn')?.addEventListener('click',showExport);$$('[data-stat]').forEach(b=>b.onclick=()=>showStat(b.dataset.stat));bindActions();
}
function formData(form){return Object.fromEntries([...new FormData(form)].filter(([,v])=>v!==''))}
function bindServiceForm(){const f=$('#serviceForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const data=formData(f),type=f.dataset.kind,id=f.dataset.id,patient=state.patients.find(p=>p.id===data.patientId);if(patient)data.patientName=patient.name;data.type=type;const addCalendar=data.calendar==='on';delete data.calendar;try{let saved;if(id){await updateRecord('services',id,data);saved={id,...data};toast('Servicio actualizado')}else{saved=await createRecord('services',data);toast('Servicio guardado')}if(addCalendar){try{const event=await createCalendarEvent({...data,title:serviceLabels[type]});await updateRecord('services',saved.id,{calendarEventId:event.id});toast('Servicio guardado y añadido a Calendar')}catch(err){console.error(err);toast('Servicio guardado; Calendar requiere autorización')}}await loadAll();navigate('historial')}catch(err){console.error(err);toast('No se pudo guardar el servicio')}}}
function bindPatientForm(){const f=$('#patientForm');f.onsubmit=async e=>{e.preventDefault();const data=formData(f),id=f.dataset.id;try{id?await updateRecord('patients',id,data):await createRecord('patients',data);closeModal();toast(id?'Paciente actualizado':'Paciente registrado');await loadAll()}catch(err){console.error(err);toast('No se pudo guardar el paciente')}}}
function bindPsychForm(){const f=$('#psychForm');f.onsubmit=async e=>{e.preventDefault();const data=formData(f),id=f.dataset.id,p=state.patients.find(x=>x.id===data.patientId);data.patientName=p?.name||'';try{id?await updateRecord('psychometrics',id,data):await createRecord('psychometrics',data);closeModal();toast(id?'Evaluación actualizada':'Evaluación registrada');await loadAll()}catch(err){console.error(err);toast('No se pudo guardar la evaluación')}}}
function bindActions(){$$('[data-edit]').forEach(b=>b.onclick=()=>editItem(b.dataset.edit,b.dataset.id));$$('[data-delete]').forEach(b=>b.onclick=()=>confirmDelete(b.dataset.delete,b.dataset.id))}
function editItem(kind,id){const arr=kind==='services'?state.services:kind==='patients'?state.patients:state.psychometrics,item=arr.find(x=>x.id===id);if(!item)return;if(kind==='services'){navigate('servicios');$('#serviceFormWrap').innerHTML=serviceForm(item.type,item);$$('[data-type]').forEach(x=>x.classList.toggle('active',x.dataset.type===item.type));bindServiceForm()}else if(kind==='patients'){openModal(patientForm(item));bindPatientForm()}else{openModal(psychForm(item));bindPsychForm()}}
function confirmDelete(kind,id){openModal(`<p class="kicker">Confirmación</p><h2>Eliminar registro</h2><p>Esta acción no se puede deshacer.</p><div class="form-actions"><button class="btn" data-close>Cancelar</button><button class="btn danger" id="deleteConfirm">Eliminar</button></div>`);$('#deleteConfirm').onclick=async()=>{try{await deleteRecord(kind,id);closeModal();toast('Registro eliminado');await loadAll()}catch(e){console.error(e);toast('No se pudo eliminar')}}}
function showExport(){openModal(`<p class="kicker">Exportación</p><h2>Selecciona el contenido</h2><form id="exportForm"><div class="form-grid"><label class="field"><span><input type="checkbox" name="services" checked> Servicios prestados</span></label><label class="field"><span><input type="checkbox" name="patients"> Pacientes</span></label><label class="field"><span><input type="checkbox" name="psychometrics"> Psicometría</span></label>${input('Desde','from','date')}${input('Hasta','to','date')}</div><div class="form-actions"><button type="button" class="btn" data-close>Cancelar</button><button class="btn primary">Descargar CSV para Excel</button></div></form>`);$('#exportForm').onsubmit=e=>{e.preventDefault();const d=formData(e.currentTarget),rows=[];if(d.services)state.services.filter(x=>(!d.from||x.date>=d.from)&&(!d.to||x.date<=d.to)).forEach(x=>rows.push({seccion:'Servicio',tipo:serviceLabels[x.type],fecha:x.date,nombre:x.patientName||x.audience||x.title||'',modalidad:x.modality||'',estado:x.status||'',observaciones:x.notes||x.reason||''}));if(d.patients)state.patients.forEach(x=>rows.push({seccion:'Paciente',tipo:x.workStatus,fecha:'',nombre:x.name,modalidad:'',estado:x.status,observaciones:x.consultationReason}));if(d.psychometrics)state.psychometrics.filter(x=>(!d.from||x.evaluationDate>=d.from)&&(!d.to||x.evaluationDate<=d.to)).forEach(x=>rows.push({seccion:'Psicometría',tipo:x.evaluationStatus,fecha:x.evaluationDate,nombre:x.patientName,modalidad:'',estado:x.reportStatus,observaciones:x.notes||''}));downloadCSV(rows);closeModal()}}
function downloadCSV(rows){if(!rows.length){toast('No hay datos para exportar');return}const keys=Object.keys(rows[0]),csv='\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`reporte-clinica-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Reporte descargado')}
function showStat(kind){let pairs=[];if(kind==='patients'){pairs=Object.entries(state.patients.reduce((a,x)=>(a[x.workStatus||'Sin categoría']=(a[x.workStatus||'Sin categoría']||0)+1,a),{}))}else if(kind==='psych'){pairs=[['Evaluadas',state.psychometrics.filter(x=>x.evaluationStatus==='Evaluada').length],['Pendientes',state.psychometrics.filter(x=>x.evaluationStatus!=='Evaluada').length],['Informes entregados',state.psychometrics.filter(x=>x.reportStatus==='Entregado').length]]}else{const rows=monthItems(state.services).filter(x=>x.type===kind),field=kind==='session'?'modality':kind==='followup'?'status':kind==='activity'?'activityType':kind==='workshop'?'modality':'status';pairs=Object.entries(rows.reduce((a,x)=>(a[x[field]||'Sin dato']=(a[x[field]||'Sin dato']||0)+1,a),{}))}const max=Math.max(...pairs.map(x=>x[1]),1);openModal(`<p class="kicker">Detalle estadístico</p><h2>${esc(kind==='psych'?'Psicometría':kind==='patients'?'Pacientes':serviceLabels[kind])}</h2>${pairs.length?pairs.map(([n,v])=>`<div class="chart-row"><span>${esc(n)}</span><div class="track"><i style="--value:${v/max*100}%"></i></div><b>${v}</b></div>`).join(''):'<div class="empty">No hay datos en este periodo.</div>'}`)}

boot();
